### ISSUE TITLE
TEI embedding error with Milvus data-prep file upload

### ISSUE THREAD

**Issue by CharleneHu-42** [opea-project/GenAIComps#564] opened 2024-08-26 08:34 UTC
After started dataprep-milvus-server with TEI embedding service, when uploading file to Milvus db with:
```bash
curl -X POST "http://${host_ip}:6010/v1/dataprep" \
     -H "Content-Type: multipart/form-data" \
     -F "files=@./nke-10k-2023.pdf"
```

TEI embedding service throws error:
```
2024-08-26T07:43:48.857102Z ERROR embed: text_embeddings_router::http::server: router/src/http/server.rs:525: batch size 270 > maximum allowed batch size 32
```

**Comment by letonghan** [comment] 2024-09-03 02:12
Caused by batch size limitation of TEI service.
Fixed by PR https://github.com/opea-project/GenAIComps/pull/570. Will close this issue.

**Closed by letonghan** 2024-09-03 02:12 UTC
Labels: DEV
