### ISSUE TITLE
Dependencies in speechT5 microservice is broken

### ISSUE THREAD

**Issue by endomorphosis** [opea-project/GenAIComps#401] opened 2024-08-02 23:13 UTC
root@laion-gaudi2-00:~/GenAIComps# docker run -p 7055:7055 --ipc=host -e http_proxy=$http_proxy -e https_proxy=$https_proxy opea/speecht5:latest
Traceback (most recent call last):
  File "/home/comps/tts/speecht5/speecht5_server.py", line 9, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

**Comment by sunnstix** [comment] 2024-08-05 00:57
Most likely duplicate of https://github.com/opea-project/GenAIComps/issues/395?

**Comment by ctao456** [comment] 2024-08-05 16:24
comment to take issue

**Comment by ctao456** [comment] 2024-08-12 05:35
This was fixed as now the [tts requirements](https://github.com/opea-project/GenAIComps/blob/main/comps/tts/requirements.txt) includes `uvicorn`. Please pull from latest branch.

**Closed** 2024-08-22 02:02 UTC
