### ISSUE TITLE
Vectorstore/pathway: CI test failed

### ISSUE THREAD

**Issue by letonghan** [opea-project/GenAIComps#741] opened 2024-09-26 01:31 UTC
- Issue
    https://github.com/opea-project/GenAIComps/actions/runs/10790149109/job/29924741234
- Description
    The `/v1/retrieve` api returns `[]` instead of `Pathway` as expected.
- Detailed logs
curl http://host_ip:5437/v1/retrieve -X POST -d '{"query":"test","k":3}' -H 'Content-Type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    24  100     2  100    22      4     45 --:--:-- --:--:-- --:--:--    49
result='[]'
[[ [] == *\P\a\t\h\w\a\y* ]]
echo 'Result wrong. Received was []'
docker logs test-comps-vectorstore-pathway-ms
Result wrong. Received was []

**Comment by XinyuYe-Intel** [comment] 2024-09-26 01:56
Hi @berkecanrizai , I saw that you added Pathway, could you check this issue?

**Comment by berkecanrizai** [comment] 2024-09-26 08:06
Hey, the issue is very likely due to the mounted path into the vector store image, which seems to be changed ([defined here](https://github.com/opea-project/GenAIComps/blob/main/tests/vectorstores/test_vectorstores_pathway.sh#L50C244-L50C291)).

For this specific test, I set `./data` folder to be mounted (mounted via the absolute path in the test) and pre-configured "data" folder as one of the inputs. I see that you moved the "pathway" folder and removed the "langchain" parent folder. Because of this, no file is mounted to the image, and when the app starts, there is no data it can ingest, thus returns an empty response to the query.

If you fix the folder in `Docker run`, this will be fixed. I can also fix it later today by branching from that PR if you want, but it should be an easy fix.

**Comment by chensuyue** [comment] 2024-09-27 06:27
I see, thanks, will fix in my PR and test it.

**Comment by chensuyue** [comment] 2024-09-27 06:38
**********Validation failed, try again**********
Invalid link from /home/runner/work/GenAIComps/GenAIComps/comps/vectorstores/pathway/README.md: https://pathway.com/developers/api-docs/pathway-io
**********Validation failed, try again**********
Invalid link from /home/runner/work/GenAIComps/GenAIComps/comps/vectorstores/pathway/README.md: https://pathway.com/developers/api-docs/pathway-xpacks-llm/vectorstore
**********Validation failed, try again**********
Invalid link from /home/runner/work/GenAIComps/GenAIComps/comps/vectorstores/pathway/README.md: https://pathway.com/developers/api-docs/pathway-xpacks-llm/parsers
**********Validation failed, try again**********
Invalid link from /home/runner/work/GenAIComps/GenAIComps/comps/vectorstores/pathway/README.md: https://pathway.com/developers/api-docs/pathway-xpacks-llm/splitters
**********Validation failed, try again**********
Invalid link from /home/runner/work/GenAIComps/GenAIComps/comps/vectorstores/pathway/README.md: https://pathway.com/developers/api-docs/pathway-xpacks-llm/embedders

**Comment by chensuyue** [comment] 2024-09-27 06:38
@berkecanrizai those links in readme seems to be invalid, could you take a look?

**Comment by berkecanrizai** [comment] 2024-09-27 07:31
@chensuyue could you re-run the pipeline? Our website was down for a brief period due to some changes, but everything should be fine now. I can confirm that the links are still valid.

**Closed** 2024-09-27 08:30 UTC
