### ISSUE TITLE
VLLM Microservice Error

### ISSUE THREAD

**Issue by wsfowler** [opea-project/GenAIComps#357] opened 2024-07-26 18:25 UTC
It looks like there is a bug in the pre-built VLLM microservice. If I launch the `opea/llm-vllm:latest` container and let Docker pull it down from Docker Hub, then I use curl to test it, I get an error:

```shell
curl http://3.82.37.51:9000/v1/chat/completions \
  -X POST \
  -d '{"query":"What is Deep Learning?","max_new_tokens":17,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":false}' \
  -H 'Content-Type: application/json'
Internal Server Error
```

If I look at the container logs:

```shell
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
[2024-07-26 16:54:01,879] [    INFO] - CORS is enabled.
[2024-07-26 16:54:01,880] [    INFO] - Setting up HTTP server
[2024-07-26 16:54:01,880] [    INFO] - Uvicorn server setup on port 9000
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
[2024-07-26 16:54:01,890] [    INFO] - HTTP server setup successful
[*** telemetry ***] post_process_text under telemetry.
INFO:     192.55.54.43:4830 - "POST /v1/completions HTTP/1.1" 404 Not Found
INFO:     192.55.54.43:6968 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/user/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused
```

If I clone the GenAIComps repo and build the container based on the latest code, my curl command works and no errors in the container logs.

```shell
root@ip-172-31-18-195:/opt/GenAIExamples/ChatQnA/docker/xeon# curl http://3.82.37.51:9000/v1/chat/completions \
  -X POST \
  -d '{"query":"What is Deep Learning?","max_new_tokens":17,"top_k":10,"top_p":0.95,"typical_p":0.95,"temperature":0.01,"repetition_penalty":1.03,"streaming":false}' \
  -H 'Content-Type: application/json'
{"id":"e457b2c763ada1560df09c976b674403","text":"\n\nDeep Learning is a subset of Machine Learning that is concerned with algorithms inspired by","prompt":"What is Deep Learning?"}
```

This container needs to be updated in Docker Hub.

**Comment by devpramod** [comment] 2024-07-30 23:35
hi @wsfowler 
Could you please confirm if you tried pulling `opea/llm-vllm:latest` based on the README instructions or without referring to the README?

**Comment by mkbhanda** [comment] 2024-07-31 02:29
Are we going to do a minor release for such bugs or do we plan to release note such "Known Issues" and offer workarounds where possible?

**Comment by wsfowler** [comment] 2024-07-31 14:40
> hi @wsfowler Could you please confirm if you tried pulling `opea/llm-vllm:latest` from dockerhub based on the README instructions or without referring to the README?

The errors I get are from when I pulled the latest `opea/llm-vllm:latest` from dockerhub. If I build the container following the readme, then I don't get the error.

**Comment by devpramod** [comment] 2024-08-01 15:19
@kevinintel I am able to reproduce this error. As @wsfowler mentioned, it only occurs when the image is pulled from dockerhub.
I ran a copy of `llm.py` from the docker hub container at port 9001 and it worked. The issue only occurs in the default code. I am unable to debug the default code further because of permission issues.

@mkbhanda Since the error is occurring only in the image downloaded from the dockerhub, we may not need any minor releases or "Known Issues".  @kevinintel please comment.

**Comment by kevinintel** [comment] 2024-08-02 01:11
If latest code is good and docker from dockerhub can't work, the most important thing is pushing correct docker instead of release. But it need some processes....

**Comment by chensuyue** [comment] 2024-08-02 01:14
@devpramod  could you try with v0.8 see if this tag works?

**Comment by chensuyue** [comment] 2024-08-05 01:36
Can we close this issue? The docker images for v0.8 will be released after the release process pass.

**Closed** 2024-08-05 14:28 UTC
Labels: DEV
